### ISSUE TITLE
ITP method

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/roots-fortran#17]
I’ve not heard of this one before: https://en.wikipedia.org/wiki/ITP_method

**Comment by ivan-pi** [comment]
It looks quite new:
> Oliveira, I. F., & Takahashi, R. H. (2020). An enhancement of the bisection method average performance preserving minmax optimality. ACM Transactions on Mathematical Software (TOMS), 47(1), 1-24. https://doi.org/10.1145/3423597

A Rust implementation is available: https://docs.rs/kurbo/0.8.1/kurbo/common/fn.solve_itp.html

**Comment by ivan-pi** [comment]
Chapter 2 in the [thesis of I.F.D. de Oliveira (2021)](https://www.ppgee.ufmg.br/defesas/1814D.PDF) is devoted to explaining the method and also provides pseudo code on page 41.
