### ISSUE TITLE
Are polynomial roots in scope?

### ISSUE THREAD

**Issue by ivan-pi** [jacobwilliams/roots-fortran#19]
In the spirit of question #4, are root finders for polynomials (both real and complex) also in scope? 

Examples from various other languages:
* R: [polyroot](https://stat.ethz.ch/R-manual/R-devel/library/base/html/polyroot.html)
* MATLAB: [roots](https://www.mathworks.com/help/matlab/ref/roots.html)
* C: [GSL - Polynomials](https://www.gnu.org/software/gsl/doc/html/poly.html), [MPSolve](https://numpi.dm.unipi.it/software/mpsolve)
* Julia: [PolynomialRoots.jl](https://github.com/giordano/PolynomialRoots.jl), [FastPolynomialRoots.jl](https://github.com/andreasnoack/FastPolynomialRoots.jl), [Polynomials.jl](https://github.com/JuliaMath/Polynomials.jl)
* Python: [numpy.polynomial.polynomial](https://docs.scipy.org/doc//numpy-1.10.4/reference/routines.polynomials.polynomial.html)

Other resources:
* [Root-finding algorithms: Roots of Polynomials | Wikipedia](https://en.wikipedia.org/wiki/Root-finding_algorithms#Roots_of_polynomials)
* [Polynomial Roots | Wolfram MathWorld](https://mathworld.wolfram.com/PolynomialRoots.html)
* [What is a Companion Matrix | Nick Higham](https://nhigham.com/2021/03/23/what-is-a-companion-matrix/)
* [19 Dubious Ways to Compute the Zeros of a Polynomial | Cleve's Corner](https://blogs.mathworks.com/cleve/2016/06/27/19-dubious-ways-to-compute-the-zeros-of-a-polynomial/)
* [New Progress in Polynomial Root-finding | Victor Y. Pan](https://arxiv.org/pdf/1805.12042.pdf)

An assortment of methods (predominantly implemented in Fortran) can be found under the [GAMS Class F1a](https://gams.nist.gov/cgi-bin/serve.cgi/Class/F1a). The most famous of these are probably the subroutines `RPOLY` and `CPOLY` from Jenkins and Traub (1975) which can be found on Netlib. Newer methods have also been written in Fortran, including `qralg.f` (part of [`/opt/companion.tgz`](https://netlib.org/opt/companion.tgz) on Netlib) from [Edelman & Murakami (1995)](https://www.ams.org/journals/mcom/1995-64-210/S0025-5718-1995-1262279-2/S0025-5718-1995-1262279-2.pdf), the [Codes from Skowron & Gould (2012)](http://www.astrouw.edu.pl/~jskowron/cmplx_roots_sg/) and [eiscor - eigensolvers based on unitary core transformations](https://github.com/eiscor/eiscor) containing the AMVW method from the work of [Aurentz et al. (2015), Fast and Backward Stable Computation of Roots of Polynomials](https://doi.org/10.1137/140983434) (an earlier version can be picked up from [the website of Ran Vandebril](https://people2.cs.kuleuven.be/~raf.vandebril/homepage/software/companion_qr.php?menu=5), one of the co-authors of that paper). The Julia packages are actually ports of these Fortran codes.

I demonstrated [a solver using the companion matrix and LAPACK](https://fortran-lang.discourse.group/t/cardanos-solution-of-the-cubic-equation/111/5?u=ivanpribec) on Discourse a while ago, but I understand that more specialized methods perform better in terms of accuracy and speed for ill-conditioned or large problems. The blog post from Cleve Moler at Cleve's Corner discusses his decision to use the companion matrix approach for MATLAB's `roots`.

Personally, I think a separate package might be more suitable as tests for polynomials roots would require different infrastructure, and in general the solvers might require more linear-algebra machinery.

**Comment by jacobwilliams** [comment]
I'm thinking maybe a separate package? Since as you say, it's a different kind of solver that will need different infrastructure. Right now this library is focused on 1d, general function, derivative free.

**Comment by jacobwilliams** [comment]
How about this?: https://github.com/jacobwilliams/polyroots-fortran

If you don't mind, I added your refs to the readme. This is just a skeleton project right now, it doesn't have any code yet.

**Comment by ivan-pi** [comment]
Looks good to me, I like the name polyroots. I hope the references will be useful. In my own projects, I've only ever needed polynomials up to order 5, but judging by the amount of work in this field, there are numerous applications.

Perhaps once polyroots are more than just a skeleton, you can add a bullet point to the [Notes](https://github.com/jacobwilliams/roots-fortran#notes) section of this library.
