### ISSUE TITLE
itp subroutine failure on inputs

### ISSUE THREAD

**Issue by ggerber** [jacobwilliams/roots-fortran#25]
Good day,

The itp subroutine fails for the following arguments:
```
ax=0
bx=157.08
f(ax)=1012
f(bx)=-1114
```
these values result in the variable "term" on line 2536 of root_module.F90 to become negative.
Then on line 2537 log(term) is evaluated, which causes the algorithm to exit prematurely.

**Comment by ivan-pi** [comment]
https://github.com/jacobwilliams/roots-fortran/blob/6ee8d35618ae5edfb46d478ef69a939c419aca5e/src/root_module.F90#L2523-L2537

Looks like replacing `b-a` with `abs(b-a)` would do the trick. I don't know enough about the algorithm to understand why `ax` and `bx` are flipped at the beginning.

**Comment by jacobwilliams** [comment]
Thanks for reporting this. I think there was some comment in the paper that f(a) must be < f(b) so I swap them if they aren't. Probably I messed something up or the paper wasn't clear about this. Will look into it.
