### ISSUE TITLE
Multi-dimensional root-finding

### ISSUE THREAD

**Issue by epagone** [jacobwilliams/roots-fortran#6]
Again, I don't know if this is in scope with the goal of the project, but it would be nice to have a similar interface to solve also systems of nonlinear equations (Newton-Raphson, Broyden's, Powell's methods, etc...).

**Comment by jacobwilliams** [comment]
Maybe that should be a separate library (or set of libraries)?

**Comment by epagone** [comment]
:+1:  Do you think the project should be then renamed something along the lines of `scalar-roots-fortran`?
